---
# tasks file for ansible_galaxy_role_ubuntu-google_chrome

- name: "Google Chrome | check apt file exists"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  stat:
    path: "{{ google_chrome.apt_file.path }}"
  register: google_chrome_apt_file

- block:

  - name: "Google Chrome | add key"
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
    shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -

  - name: "Google Chrome | add repository"
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
    copy:
      content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
      dest: "{{ google_chrome.apt_file.path }}"
      owner: root 
      group: root
      mode: "0644"

  - name: "Google Chrome | update apt cache"
    become: yes
    ignore_errors: "{{ ansible_check_mode }}"
    apt:
      update_cache: yes

  when: not google_chrome_apt_file.stat.exists

- name: "Google Chrome | install"
  become: yes
  ignore_errors: "{{ ansible_check_mode }}"
  apt:
    name: google-chrome-stable 
    state: present
